version: '3.7'

services:
 hits:
  build: .
  image: hits:compose
  labels:
   - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
  depends_on:
   - redis
  networks:
   - public
   - secret
  volumes:
   - logs:/flask/logs
  deploy:
   mode: replicated
   replicas: 3
 redis:
  image: redis:alpine
  volumes:
   - redis-data:/data 
  networks:
   - secret
 loadbalancer:
  image: traefik:v1.7.19-alpine
  command: --docker
  labels:
    - "traefik.http.services.loadbalancer.loadbalancer.server.port=80"
  links:
   - hits
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  ports:
   - 8080:80
  networks:
   - public

volumes:
 redis-data:
  driver: local
 logs:
  driver: local
networks:
 secret:
  driver: bridge
 public:
  driver: bridge
